export const TRANSLATIONS = {
    vi: {
        title: "KẾ HOẠCH TIẾN ĐỘ DỰ ÁN MOST",
        subtitle: "Đồng bộ 100% nội dung Excel - Đánh số từ 0",
        startDate: "Ngày Bắt Đầu",
        durationMonths: "Quy mô (Tháng)",
        exportBtn: "Xuất CSV (Dạng Lưới)",
        saveJson: "Lưu Project (.json)",
        loadJson: "Mở Project",
        howTo: "Hướng dẫn tương tác",
        overview: "Thông số dự án",
        totalWeeks: "Tổng thời gian",
        milestones: "Mốc thanh toán",
        status: "Trạng thái",
        ready: "Sẵn sàng",
        weeks: "tuần",
        month: "Tháng",
        config: "Cấu hình",
        no: "No.",
        item: "Nội dung công việc / Thanh toán",
        startWeek: "Bắt đầu",
        duration: "Số tuần",
        onsite: "Onsite",
        actions: "Thao tác",
        addSub: "Thêm mục con",
        guide1: "📋 Đánh số WBS tự động — hệ thống tự đánh số (0, 1, 1.1, 1.2...) khi thêm/xóa/sắp xếp.",
        guide2: "➕ Thêm mục con — hover vào task chính, nhấn '+ Sub' để thêm sub-task ngay bên dưới.",
        guide3: "☰ Kéo thả sắp xếp — giữ icon ☰ để kéo task lên/xuống. Số hiệu tự cập nhật.",
        guide4: "🖱️ Click vào thanh bar — kéo trái/phải để dời, kéo cạnh phải để resize.",
        guide5: "🔵 Onsite marker — bật 'Onsite' để hiện ký tự 'O' ở tất cả tuần của task.",
        guide6: "↩️ Undo / Redo — Ctrl+Z hoàn tác, Ctrl+Y làm lại. Hỗ trợ nhiều bước.",
        guide7: "🔍 Zoom — dùng nút +/- để phóng to thu nhỏ. Nhấn 📐 để tự fit màn hình.",
        guide8: "📅 Double-click tháng — double-click vào header tháng để thu gọn/mở rộng cột tuần.",
        guide9: "☑️ Multi-select — click checkbox để chọn nhiều task → đổi màu / dời / xóa hàng loạt.",
        guide10: "🎨 Đổi màu — click vào chấm màu bên trái tên task để chọn màu mới cho cả nhóm.",
        guide11: "📥 Export — xuất file Excel, PDF hoặc PNG với tên dự án hiển thị đầy đủ.",
        guide12: "💾 Auto-save — hệ thống tự lưu mỗi thay đổi. Mở lại trang = thấy data mới nhất.",
        guide13: "📂 Save/Load — lưu project thành file .json để chia sẻ hoặc mở trên máy khác.",
        guide14: "🌙 Dark mode & 🌐 Ngôn ngữ — chuyển đổi giao diện tối/sáng và VI/EN.",
        guideEditCat: "✏️ Chỉnh sửa",
        guideViewCat: "👁️ Hiển thị",
        guideDataCat: "💾 Dữ liệu",
        guideStyleCat: "🎨 Giao diện"
    },
    en: {
        title: "MOST PROJECT SCHEDULE",
        subtitle: "100% Excel Copy - Numbering from 0",
        startDate: "Start Date",
        durationMonths: "Scale (Months)",
        exportBtn: "Export CSV (Grid)",
        saveJson: "Save (.json)",
        loadJson: "Load Project",
        howTo: "Interactive Guide",
        overview: "Overview",
        totalWeeks: "Total Duration",
        milestones: "Payments",
        status: "Status",
        ready: "Ready",
        weeks: "weeks",
        month: "Month",
        config: "Config",
        no: "No.",
        item: "Work Content / Payments",
        startWeek: "Start",
        duration: "Weeks",
        onsite: "Onsite",
        actions: "Actions",
        addSub: "Add Sub",
        guide1: "📋 Auto WBS numbering — system auto-numbers (0, 1, 1.1...) on add/delete/reorder.",
        guide2: "➕ Add sub-task — hover a main task, click '+ Sub' to insert a child below.",
        guide3: "☰ Drag to reorder — hold ☰ to drag tasks. Numbers update automatically.",
        guide4: "🖱️ Click bar — drag left/right to move, drag right edge to resize.",
        guide5: "🔵 Onsite marker — enable 'Onsite' to show 'O' on all weeks of a task.",
        guide6: "↩️ Undo / Redo — Ctrl+Z to undo, Ctrl+Y to redo. Multi-step support.",
        guide7: "🔍 Zoom — use +/- buttons to zoom. Click 📐 to fit screen.",
        guide8: "📅 Double-click month — double-click month header to collapse/expand week columns.",
        guide9: "☑️ Multi-select — click checkboxes to select tasks → batch color/move/delete.",
        guide10: "🎨 Change color — click the color dot next to a task name to pick a new color.",
        guide11: "📥 Export — export to Excel, PDF, or PNG with full project name displayed.",
        guide12: "💾 Auto-save — all changes are saved automatically. Reload = latest data.",
        guide13: "📂 Save/Load — save project as .json to share or open on another machine.",
        guide14: "🌙 Dark mode & 🌐 Language — switch between dark/light and VI/EN.",
        guideEditCat: "✏️ Editing",
        guideViewCat: "👁️ View",
        guideDataCat: "💾 Data",
        guideStyleCat: "🎨 Appearance"
    }
};

export const INITIAL_DATA = [
    { id: 't0', nameVi: 'Hợp đồng dự án', nameEn: 'Project Contract', startWeek: 0, duration: 1, type: 'task', level: 0, isOnsite: false },

    { id: 't1', nameVi: 'Khởi động dự án', nameEn: 'Project Kick-off', startWeek: 1, duration: 1, type: 'task', level: 0, isOnsite: true },
    { id: 't1.1', nameVi: 'Thành lập ban quản lý dự án', nameEn: 'Project Management Team establishment', startWeek: 1, duration: 1, type: 'task', level: 1, isOnsite: true },
    { id: 't1.2', nameVi: 'Lập kế hoạch dự án chi tiết', nameEn: 'Detailed project planning', startWeek: 1, duration: 1, type: 'task', level: 1, isOnsite: true },
    { id: 't1.3', nameVi: 'Họp khởi động dự án (Kick-off meeting)', nameEn: 'Kick-off meeting', startWeek: 1, duration: 1, type: 'task', level: 1, isOnsite: true },

    { id: 'p1', nameVi: 'Thanh toán Đợt 1: Tạm ứng hợp đồng (30%)', nameEn: 'Payment 1: Advance (30%)', type: 'payment', startWeek: 1, level: 0 },

    { id: 't2', nameVi: 'Phân tích hệ thống', nameEn: 'System Analysis', startWeek: 2, duration: 4, type: 'task', level: 0, isOnsite: true },
    { id: 't2.1', nameVi: 'Khảo sát hiện trạng', nameEn: 'Site Survey', startWeek: 2, duration: 2, type: 'task', level: 1, isOnsite: true },
    { id: 't2.2', nameVi: 'Phân tích yêu cầu', nameEn: 'Requirement Analysis', startWeek: 3, duration: 2, type: 'task', level: 1, isOnsite: true },
    { id: 't2.3', nameVi: 'Tài liệu giải pháp (Solution Document)', nameEn: 'Solution Document', startWeek: 4, duration: 2, type: 'task', level: 1, isOnsite: true },

    { id: 't3', nameVi: 'Thiết kế hệ thống', nameEn: 'System Design', startWeek: 6, duration: 4, type: 'task', level: 0, isOnsite: false },
    { id: 't3.1', nameVi: 'Thiết kế cơ sở dữ liệu', nameEn: 'Database Design', startWeek: 6, duration: 2, type: 'task', level: 1, isOnsite: false },
    { id: 't3.2', nameVi: 'Thiết kế giao diện (UI/UX)', nameEn: 'UI/UX Design', startWeek: 7, duration: 2, type: 'task', level: 1, isOnsite: false },

    { id: 't4', nameVi: 'Chỉnh sửa hệ thống', nameEn: 'System Modification', startWeek: 10, duration: 4, type: 'task', level: 0, isOnsite: false },
    { id: 't4.1', nameVi: 'Cập nhật logic nghiệp vụ', nameEn: 'Update Business Logic', startWeek: 10, duration: 3, type: 'task', level: 1, isOnsite: false },
    { id: 'p2', nameVi: 'Thanh toán Đợt 2: Hoàn thành việc thiết kế và chỉnh sửa hệ thống (30%)', nameEn: 'Payment 2: Design & Modification Complete (30%)', type: 'payment', startWeek: 14, level: 0 },

    { id: 't5', nameVi: 'Phát triển hệ thống', nameEn: 'System Development', startWeek: 14, duration: 8, type: 'task', level: 0, isOnsite: true },

    { id: 't6', nameVi: 'Thực hiện hệ thống', nameEn: 'System Implementation', startWeek: 22, duration: 6, type: 'task', level: 0, isOnsite: true },
    { id: 't6.1', nameVi: 'Cài đặt hệ thống', nameEn: 'System Installation', startWeek: 22, duration: 2, type: 'task', level: 1, isOnsite: true },
    { id: 't6.2', nameVi: 'Đào tạo người dùng cấp cao (super user)', nameEn: 'Super User Training', startWeek: 23, duration: 1, type: 'task', level: 1, isOnsite: true },
    { id: 't6.3', nameVi: 'Thực hiện UAT(User Acceptant testing), kiểm thử chấp nhân của người dùng', nameEn: 'UAT Execution', startWeek: 24, duration: 4, type: 'task', level: 1, isOnsite: true },
    { id: 't6.4', nameVi: 'Đào tạo người dùng cuối (end user) từ người dùng cao cấp (super user)', nameEn: 'End User Training', startWeek: 27, duration: 1, type: 'task', level: 1, isOnsite: true },
    { id: 'p3', nameVi: 'Thanh toán Đợt 3: Hoàn thành việc thực thi hệ thống (20%)', nameEn: 'Payment 3: Implementation Complete (20%)', type: 'payment', startWeek: 28, level: 0 },

    { id: 't7', nameVi: 'Triển khai hệ thống', nameEn: 'System Roll-out', startWeek: 28, duration: 4, type: 'task', level: 0, isOnsite: true },
    { id: 't7.1', nameVi: 'Field Test and Preparation for Go-Live (Thực hiện kiểm thử và chuẩn bị Go-live)', nameEn: 'Field Test & Preparation', startWeek: 28, duration: 2, type: 'task', level: 1, isOnsite: true },
    { id: 't7.2', nameVi: 'Triển khai hệ thống (Roll-out)', nameEn: 'Roll-out', startWeek: 30, duration: 2, type: 'task', level: 1, isOnsite: true },

    { id: 'p4', nameVi: 'Thanh Toán Đợt 4: Hoàn thành triển khai hệ thống (10%)', nameEn: 'Payment 4: Roll-out Complete (10%)', type: 'payment', startWeek: 31, level: 0 },
    { id: 't7.3', nameVi: 'Gửi hỗ trợ triển khai hệ thống (support Roll-out)', nameEn: 'Support Roll-out', startWeek: 32, duration: 1, type: 'task', level: 1, isOnsite: true },
    { id: 'p5', nameVi: 'Thanh toán Đợt 5: Ký giấy chứng nhận nghiệm thu (10%)', nameEn: 'Payment 5: Final Acceptance (10%)', type: 'payment', startWeek: 33, level: 0 },
];
